// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graph

import (
	"time"
)

type Account struct {
	ID          string  `json:"id"`
	AccountName string  `json:"accountName"`
	Balance     float64 `json:"balance"`
	User        *User   `json:"user,omitempty"`
}

type CreateUserInput struct {
	FirstName string  `json:"firstName"`
	LastName  string  `json:"lastName"`
	Phone     string  `json:"phone"`
	Email     *string `json:"email,omitempty"`
}

type Result struct {
	Success bool        `json:"success"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type Transaction struct {
	ID                     string    `json:"id"`
	Reference              string    `json:"reference"`
	Description            string    `json:"description"`
	SourceAccountID        string    `json:"sourceAccountId"`
	SourceAccountName      string    `json:"sourceAccountName"`
	DestinationAccountID   string    `json:"destinationAccountId"`
	DestinationAccountName string    `json:"destinationAccountName"`
	Amount                 float64   `json:"amount"`
	BalanceBeforeCredit    float64   `json:"balanceBeforeCredit"`
	BalanceAfterCredit     float64   `json:"balanceAfterCredit"`
	BalanceBeforeDebit     float64   `json:"balanceBeforeDebit"`
	BalanceAfterDebit      float64   `json:"balanceAfterDebit"`
	TimeCreated            time.Time `json:"timeCreated"`
	TimeUpdated            time.Time `json:"timeUpdated"`
}

type TransferFundsInput struct {
	FromAccountID string  `json:"fromAccountId"`
	ToAccountID   string  `json:"toAccountId"`
	Amount        float64 `json:"amount"`
	Description   string  `json:"description"`
}

type User struct {
	ID          string    `json:"id"`
	FirstName   string    `json:"firstName"`
	LastName    string    `json:"lastName"`
	Email       string    `json:"email"`
	Phone       string    `json:"phone"`
	TimeCreated time.Time `json:"timeCreated"`
	TimeUpdated time.Time `json:"timeUpdated"`
}
